services:
  api:
    build: .
    container_name: podcast_manager_api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules # Evita que o volume sobrescreva os pacotes instalados no container
    environment:
      - NODE_ENV=development
    restart: always